services:
  mysql:
    build: .
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      TZ: Asia/Tokyo
    volumes:
      - "db-store:/var/lib/mysql"
  minio:
    image: minio/minio:RELEASE.2023-01-06T18-11-18Z
    command: [ "server", "/data", "--console-address", ":9090" ]
    volumes:
      - "minio:/data"
    environment:
      - MINIO_ROOT_USER=minio_root
      - MINIO_ROOT_PASSWORD=minio_password
    ports:
      - "9000:9000"
      - "9090:9090"

volumes:
  db-store:
  minio:
    driver: local