"""empty message

Revision ID: 2e6fa4ba081c
Revises: dad989810671
Create Date: 2023-04-20 23:53:50.786122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6fa4ba081c'
down_revision = 'dad989810671'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controlnet_illustrations', sa.Column('controlnet_model_id', sa.Integer(), nullable=False))
    op.drop_constraint('unique_controlnet_illustrations', 'controlnet_illustrations', type_='unique')
    op.create_unique_constraint('unique_controlnet_illustrations', 'controlnet_illustrations', ['num_inference_steps', 'guidance_scale', 'controlnet_conditioning_scale', 'parent_image', 'illustration_prompt_id', 'illustration_negative_prompt_id', 'illustration_model_id', 'controlnet_model_id'])
    op.create_foreign_key(None, 'controlnet_illustrations', 'controlnet_models', ['controlnet_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'controlnet_illustrations', type_='foreignkey')
    op.drop_constraint('unique_controlnet_illustrations', 'controlnet_illustrations', type_='unique')
    op.create_unique_constraint('unique_controlnet_illustrations', 'controlnet_illustrations', ['num_inference_steps', 'guidance_scale', 'controlnet_conditioning_scale', 'parent_image', 'illustration_prompt_id', 'illustration_negative_prompt_id', 'illustration_model_id'])
    op.drop_column('controlnet_illustrations', 'controlnet_model_id')
    # ### end Alembic commands ###
