"""empty message

Revision ID: 56eeb6916329
Revises: 71ea8391a09f
Create Date: 2023-04-19 04:17:39.867556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56eeb6916329'
down_revision = '71ea8391a09f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controlnet_illustrations', sa.Column('parent_image', sa.String(length=255), nullable=False))
    op.drop_constraint('unique_controlnet_illustrations', 'controlnet_illustrations', type_='unique')
    op.create_unique_constraint('unique_controlnet_illustrations', 'controlnet_illustrations', ['num_inference_steps', 'guidance_scale', 'controlnet_conditioning_scale', 'parent_image', 'illustration_prompt_id', 'illustration_negative_prompt_id', 'illustration_model_id'])
    op.drop_column('controlnet_illustrations', 'image')
    op.add_column('img2img_illustrations', sa.Column('parent_image', sa.String(length=255), nullable=False))
    op.drop_constraint('unique_img2img_illustrations', 'img2img_illustrations', type_='unique')
    op.create_unique_constraint('unique_img2img_illustrations', 'img2img_illustrations', ['num_inference_steps', 'guidance_scale', 'strength', 'parent_image', 'illustration_prompt_id', 'illustration_negative_prompt_id', 'illustration_model_id'])
    op.drop_column('img2img_illustrations', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('img2img_illustrations', sa.Column('image', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
    op.drop_constraint('unique_img2img_illustrations', 'img2img_illustrations', type_='unique')
    op.create_unique_constraint('unique_img2img_illustrations', 'img2img_illustrations', ['num_inference_steps', 'guidance_scale', 'strength', 'image', 'illustration_prompt_id', 'illustration_negative_prompt_id', 'illustration_model_id'])
    op.drop_column('img2img_illustrations', 'parent_image')
    op.add_column('controlnet_illustrations', sa.Column('image', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False))
    op.drop_constraint('unique_controlnet_illustrations', 'controlnet_illustrations', type_='unique')
    op.create_unique_constraint('unique_controlnet_illustrations', 'controlnet_illustrations', ['num_inference_steps', 'guidance_scale', 'controlnet_conditioning_scale', 'image', 'illustration_prompt_id', 'illustration_negative_prompt_id', 'illustration_model_id'])
    op.drop_column('controlnet_illustrations', 'parent_image')
    # ### end Alembic commands ###
