"""empty message

Revision ID: 71ea8391a09f
Revises: 383cd355e399
Create Date: 2023-04-18 17:20:45.123513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ea8391a09f'
down_revision = '383cd355e399'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controlnet_illustration_images', sa.Column('controlnet_illustration_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_controlnet_illustration_images', 'controlnet_illustration_images', ['seed', 'controlnet_illustration_id'])
    op.create_unique_constraint(None, 'controlnet_illustration_images', ['image'])
    op.create_foreign_key(None, 'controlnet_illustration_images', 'controlnet_illustrations', ['controlnet_illustration_id'], ['id'])
    op.add_column('controlnet_illustration_posts', sa.Column('controlnet_illustration_image_id', sa.Integer(), nullable=False))
    op.add_column('controlnet_illustration_posts', sa.Column('illustration_post_group_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_controlnet_illustration_posts', 'controlnet_illustration_posts', ['controlnet_illustration_image_id', 'illustration_post_group_id'])
    op.create_foreign_key(None, 'controlnet_illustration_posts', 'controlnet_illustration_images', ['controlnet_illustration_image_id'], ['id'])
    op.create_foreign_key(None, 'controlnet_illustration_posts', 'illustration_post_groups', ['illustration_post_group_id'], ['id'])
    op.add_column('controlnet_illustrations', sa.Column('illustration_prompt_id', sa.Integer(), nullable=False))
    op.add_column('controlnet_illustrations', sa.Column('illustration_negative_prompt_id', sa.Integer(), nullable=False))
    op.add_column('controlnet_illustrations', sa.Column('illustration_model_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_controlnet_illustrations', 'controlnet_illustrations', ['num_inference_steps', 'guidance_scale', 'controlnet_conditioning_scale', 'image', 'illustration_prompt_id', 'illustration_negative_prompt_id', 'illustration_model_id'])
    op.create_foreign_key(None, 'controlnet_illustrations', 'illustration_prompts', ['illustration_negative_prompt_id'], ['id'])
    op.create_foreign_key(None, 'controlnet_illustrations', 'illustration_prompts', ['illustration_prompt_id'], ['id'])
    op.create_foreign_key(None, 'controlnet_illustrations', 'illustration_models', ['illustration_model_id'], ['id'])
    op.add_column('img2img_illustration_images', sa.Column('img2img_illustration_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_img2img_illustration_images', 'img2img_illustration_images', ['seed', 'img2img_illustration_id'])
    op.create_foreign_key(None, 'img2img_illustration_images', 'img2img_illustrations', ['img2img_illustration_id'], ['id'])
    op.add_column('img2img_illustration_posts', sa.Column('img2img_illustration_image_id', sa.Integer(), nullable=False))
    op.add_column('img2img_illustration_posts', sa.Column('illustration_post_group_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_img2img_illustration_posts', 'img2img_illustration_posts', ['img2img_illustration_image_id', 'illustration_post_group_id'])
    op.create_foreign_key(None, 'img2img_illustration_posts', 'illustration_post_groups', ['illustration_post_group_id'], ['id'])
    op.create_foreign_key(None, 'img2img_illustration_posts', 'img2img_illustration_images', ['img2img_illustration_image_id'], ['id'])
    op.add_column('img2img_illustrations', sa.Column('illustration_prompt_id', sa.Integer(), nullable=False))
    op.add_column('img2img_illustrations', sa.Column('illustration_negative_prompt_id', sa.Integer(), nullable=False))
    op.add_column('img2img_illustrations', sa.Column('illustration_model_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_img2img_illustrations', 'img2img_illustrations', ['num_inference_steps', 'guidance_scale', 'strength', 'image', 'illustration_prompt_id', 'illustration_negative_prompt_id', 'illustration_model_id'])
    op.create_foreign_key(None, 'img2img_illustrations', 'illustration_prompts', ['illustration_prompt_id'], ['id'])
    op.create_foreign_key(None, 'img2img_illustrations', 'illustration_prompts', ['illustration_negative_prompt_id'], ['id'])
    op.create_foreign_key(None, 'img2img_illustrations', 'illustration_models', ['illustration_model_id'], ['id'])
    op.add_column('txt2img_illustration_images', sa.Column('txt2img_illustration_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_txt2img_illustration_images', 'txt2img_illustration_images', ['seed', 'txt2img_illustration_id'])
    op.create_foreign_key(None, 'txt2img_illustration_images', 'txt2img_illustrations', ['txt2img_illustration_id'], ['id'])
    op.add_column('txt2img_illustration_posts', sa.Column('txt2img_illustration_image_id', sa.Integer(), nullable=False))
    op.add_column('txt2img_illustration_posts', sa.Column('illustration_post_group_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_txt2img_illustration_posts', 'txt2img_illustration_posts', ['txt2img_illustration_image_id', 'illustration_post_group_id'])
    op.create_foreign_key(None, 'txt2img_illustration_posts', 'txt2img_illustration_images', ['txt2img_illustration_image_id'], ['id'])
    op.create_foreign_key(None, 'txt2img_illustration_posts', 'illustration_post_groups', ['illustration_post_group_id'], ['id'])
    op.add_column('txt2img_illustrations', sa.Column('illustration_prompt_id', sa.Integer(), nullable=False))
    op.add_column('txt2img_illustrations', sa.Column('illustration_negative_prompt_id', sa.Integer(), nullable=False))
    op.add_column('txt2img_illustrations', sa.Column('illustration_model_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_txt2img_illustrations', 'txt2img_illustrations', ['num_inference_steps', 'guidance_scale', 'height', 'width', 'illustration_prompt_id', 'illustration_negative_prompt_id', 'illustration_model_id'])
    op.create_foreign_key(None, 'txt2img_illustrations', 'illustration_prompts', ['illustration_negative_prompt_id'], ['id'])
    op.create_foreign_key(None, 'txt2img_illustrations', 'illustration_prompts', ['illustration_prompt_id'], ['id'])
    op.create_foreign_key(None, 'txt2img_illustrations', 'illustration_models', ['illustration_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'txt2img_illustrations', type_='foreignkey')
    op.drop_constraint(None, 'txt2img_illustrations', type_='foreignkey')
    op.drop_constraint(None, 'txt2img_illustrations', type_='foreignkey')
    op.drop_constraint('unique_txt2img_illustrations', 'txt2img_illustrations', type_='unique')
    op.drop_column('txt2img_illustrations', 'illustration_model_id')
    op.drop_column('txt2img_illustrations', 'illustration_negative_prompt_id')
    op.drop_column('txt2img_illustrations', 'illustration_prompt_id')
    op.drop_constraint(None, 'txt2img_illustration_posts', type_='foreignkey')
    op.drop_constraint(None, 'txt2img_illustration_posts', type_='foreignkey')
    op.drop_constraint('unique_txt2img_illustration_posts', 'txt2img_illustration_posts', type_='unique')
    op.drop_column('txt2img_illustration_posts', 'illustration_post_group_id')
    op.drop_column('txt2img_illustration_posts', 'txt2img_illustration_image_id')
    op.drop_constraint(None, 'txt2img_illustration_images', type_='foreignkey')
    op.drop_constraint('unique_txt2img_illustration_images', 'txt2img_illustration_images', type_='unique')
    op.drop_column('txt2img_illustration_images', 'txt2img_illustration_id')
    op.drop_constraint(None, 'img2img_illustrations', type_='foreignkey')
    op.drop_constraint(None, 'img2img_illustrations', type_='foreignkey')
    op.drop_constraint(None, 'img2img_illustrations', type_='foreignkey')
    op.drop_constraint('unique_img2img_illustrations', 'img2img_illustrations', type_='unique')
    op.drop_column('img2img_illustrations', 'illustration_model_id')
    op.drop_column('img2img_illustrations', 'illustration_negative_prompt_id')
    op.drop_column('img2img_illustrations', 'illustration_prompt_id')
    op.drop_constraint(None, 'img2img_illustration_posts', type_='foreignkey')
    op.drop_constraint(None, 'img2img_illustration_posts', type_='foreignkey')
    op.drop_constraint('unique_img2img_illustration_posts', 'img2img_illustration_posts', type_='unique')
    op.drop_column('img2img_illustration_posts', 'illustration_post_group_id')
    op.drop_column('img2img_illustration_posts', 'img2img_illustration_image_id')
    op.drop_constraint(None, 'img2img_illustration_images', type_='foreignkey')
    op.drop_constraint('unique_img2img_illustration_images', 'img2img_illustration_images', type_='unique')
    op.drop_column('img2img_illustration_images', 'img2img_illustration_id')
    op.drop_constraint(None, 'controlnet_illustrations', type_='foreignkey')
    op.drop_constraint(None, 'controlnet_illustrations', type_='foreignkey')
    op.drop_constraint(None, 'controlnet_illustrations', type_='foreignkey')
    op.drop_constraint('unique_controlnet_illustrations', 'controlnet_illustrations', type_='unique')
    op.drop_column('controlnet_illustrations', 'illustration_model_id')
    op.drop_column('controlnet_illustrations', 'illustration_negative_prompt_id')
    op.drop_column('controlnet_illustrations', 'illustration_prompt_id')
    op.drop_constraint(None, 'controlnet_illustration_posts', type_='foreignkey')
    op.drop_constraint(None, 'controlnet_illustration_posts', type_='foreignkey')
    op.drop_constraint('unique_controlnet_illustration_posts', 'controlnet_illustration_posts', type_='unique')
    op.drop_column('controlnet_illustration_posts', 'illustration_post_group_id')
    op.drop_column('controlnet_illustration_posts', 'controlnet_illustration_image_id')
    op.drop_constraint(None, 'controlnet_illustration_images', type_='foreignkey')
    op.drop_constraint(None, 'controlnet_illustration_images', type_='unique')
    op.drop_constraint('unique_controlnet_illustration_images', 'controlnet_illustration_images', type_='unique')
    op.drop_column('controlnet_illustration_images', 'controlnet_illustration_id')
    # ### end Alembic commands ###
